#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Next Dockerimage

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04
    env:
      # Try to find better name to avoid confusion with two next words
      IMAGE_FULL: quay.io/eclipse/che-dashboard:next-next

    steps:
    - name: Checkout che-dashboard-next source code
      uses: actions/checkout@v2
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
    - name: Docker prepare
      run: docker image prune -a -f
    - name: Docker Quay.io Login
      # TODO upload new credentials. Currently che-incubator is used, when eclipse is needed
      run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
    - name: Build and push the Docker image(s)
      run: docker buildx build --platform linux/amd64,linux/s390x  -t ${IMAGE_FULL}  -f apache.Dockerfile --push .
    - name: Docker Logout
      run: docker logout
